apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-app
  template:
    metadata:
      labels:
        app: quiz-app
    spec:
      containers:
        - name: quiz-app
          image: 250760537264.dkr.ecr.us-east-1.amazonaws.com/quiz-app:latest
          ports:
            - containerPort: 80